---
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.90.5
    hooks:
      - id: trufflehog

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.8.1
    hooks:
      - id: ansible-lint
        args: ["-c", ".config/.ansible-lint", "users_management"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ["-c", ".config/.yamllint"]

...
