---
- name: Fetch OS dependent variables
  ansible.builtin.include_vars:
    file: "{{ item }}"
    name: os_vars
  with_first_found:
    - files:
        - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version | default() }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version | default() }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      skip: true
  tags: always

- name: Create users and groups
  ansible.builtin.import_tasks: create.yml

- name: Delete users and groups
  ansible.builtin.import_tasks: delete.yml
...
